"use client";

import { useState } from "react";
import { FileText, ExternalLink, Search, Loader2, Calendar, User } from "lucide-react";
import { getExaminerReportSignedUrl } from "@/app/(examiner)/examiner/reports/actions";

export interface ExaminerReportItem {
  id: string;
  candidateId: string;
  candidateName: string;
  reportType: string;
  generatedAt: string;
  generatedBy: string;
  fileStoragePath?: string | null;
}

const REPORT_TYPE_LABELS: Record<string, string> = {
  assessment_report: "Assessment Outcome Report",
  diagnostic_summary: "EV Diagnostic Summary",
  competency_matrix: "Competency Verification Record",
  practical_assessment: "Practical Demonstration Report",
};

export function ExaminerReportsList({ reports }: { reports: ExaminerReportItem[] }) {
  const [query, setQuery] = useState("");
  const [loadingReportId, setLoadingReportId] = useState<string | null>(null);
  const [errorMsg, setErrorMsg] = useState<{ id: string; text: string } | null>(null);

  const filtered = reports.filter(
    (r) =>
      r.candidateName.toLowerCase().includes(query.toLowerCase()) ||
      (REPORT_TYPE_LABELS[r.reportType] || r.reportType)
        .toLowerCase()
        .includes(query.toLowerCase())
  );

  const handleOpenReport = async (reportId: string) => {
    setLoadingReportId(reportId);
    setErrorMsg(null);
    const res = await getExaminerReportSignedUrl(reportId);
    setLoadingReportId(null);
    if (res.url) {
      window.open(res.url, "_blank", "noopener,noreferrer");
    } else {
      setErrorMsg({ id: reportId, text: res.error || "Could not generate report preview link." });
    }
  };

  if (reports.length === 0) {
    return (
      <div className="flex flex-col items-center justify-center rounded-xl border border-dashed border-border bg-card p-12 text-center">
        <FileText className="size-10 text-muted-foreground/50 mb-3" />
        <h3 className="text-base font-semibold text-foreground">No reports generated yet.</h3>
        <p className="mt-1 text-xs text-muted-foreground">
          Reports will appear automatically when candidates complete assessments or when competency outcomes are finalized.
        </p>
      </div>
    );
  }

  return (
    <div className="space-y-4">
      {/* Search Bar */}
      <div className="relative max-w-md">
        <Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" />
        <input
          type="text"
          value={query}
          onChange={(e) => setQuery(e.target.value)}
          placeholder="Search by candidate name or report type..."
          className="h-10 w-full rounded-lg border border-input bg-card pl-9 pr-4 text-sm text-foreground placeholder:text-muted-foreground focus:border-primary focus:outline-none focus:ring-1 focus:ring-primary"
        />
      </div>

      {filtered.length === 0 ? (
        <div className="rounded-xl border border-border bg-card p-8 text-center text-sm text-muted-foreground">
          No reports match your search criteria.
        </div>
      ) : (
        <div className="overflow-hidden rounded-xl border border-border bg-card shadow-xs">
          <table className="w-full text-left text-sm">
            <thead className="border-b border-border bg-muted/40 text-xs font-semibold uppercase text-muted-foreground">
              <tr>
                <th className="px-5 py-3.5">Candidate</th>
                <th className="px-5 py-3.5">Report Type</th>
                <th className="px-5 py-3.5">Generated Date</th>
                <th className="px-5 py-3.5">Generated By</th>
                <th className="px-5 py-3.5 text-right">Action</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-border">
              {filtered.map((r) => {
                const isLoading = loadingReportId === r.id;
                const typeLabel = REPORT_TYPE_LABELS[r.reportType] || r.reportType.replace(/_/g, " ");

                return (
                  <tr key={r.id} className="transition hover:bg-muted/40">
                    <td className="px-5 py-4">
                      <div className="flex items-center gap-2">
                        <User className="size-4 text-primary shrink-0" />
                        <span className="font-semibold text-foreground">{r.candidateName}</span>
                      </div>
                    </td>
                    <td className="px-5 py-4">
                      <span className="inline-flex items-center gap-1 text-xs font-medium text-foreground">
                        <FileText className="size-3.5 text-muted-foreground" /> {typeLabel}
                      </span>
                    </td>
                    <td className="px-5 py-4 text-xs text-muted-foreground">
                      <span className="inline-flex items-center gap-1">
                        <Calendar className="size-3.5" />
                        {new Date(r.generatedAt).toLocaleDateString("en-AU", {
                          day: "numeric",
                          month: "short",
                          year: "numeric",
                        })}
                      </span>
                    </td>
                    <td className="px-5 py-4 text-xs text-muted-foreground capitalize">
                      {r.generatedBy === "system" ? "Automated Pipeline" : r.generatedBy}
                    </td>
                    <td className="px-5 py-4 text-right">
                      {errorMsg?.id === r.id && (
                        <div className="text-[11px] text-destructive mb-1">{errorMsg.text}</div>
                      )}
                      <button
                        type="button"
                        disabled={isLoading}
                        onClick={() => handleOpenReport(r.id)}
                        className="inline-flex items-center gap-1.5 rounded-lg border border-border bg-card px-3 py-1.5 text-xs font-semibold text-primary hover:bg-primary/10 hover:border-primary/40 transition disabled:opacity-50 cursor-pointer shadow-2xs"
                      >
                        {isLoading ? (
                          <>
                            <Loader2 className="size-3.5 animate-spin" /> Loading...
                          </>
                        ) : (
                          <>
                            <ExternalLink className="size-3.5" /> View Report
                          </>
                        )}
                      </button>
                    </td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>
      )}
    </div>
  );
}
