"use client";

import React, { useState, useMemo } from "react";
import { Search, ExternalLink, Loader2, Calendar, FileText, UserCheck, AlertCircle } from "lucide-react";
import { Button } from "@/components/ui/button";
import { getAdminReportUrl } from "@/app/(admin)/admin/reports/actions";

export interface AdminReportItem {
  id: string;
  candidate_id: string;
  candidate_name: string;
  report_type: string;
  generated_by: string;
  generated_at: string;
}

interface Props {
  reports: AdminReportItem[];
}

const REPORT_TYPE_LABELS: Record<string, string> = {
  assessment_report: "Assessment Report",
  ev_readiness_report: "EV Readiness Report",
};

export function AdminReportsList({ reports }: Props) {
  const [search, setSearch] = useState("");
  const [typeFilter, setTypeFilter] = useState("all");
  const [loadingId, setLoadingId] = useState<string | null>(null);
  const [errorMsg, setErrorMsg] = useState<{ id: string; text: string } | null>(null);

  const filtered = useMemo(() => {
    return reports.filter((r) => {
      if (search && !r.candidate_name.toLowerCase().includes(search.toLowerCase())) return false;
      if (typeFilter !== "all" && r.report_type !== typeFilter) return false;
      return true;
    });
  }, [reports, search, typeFilter]);

  const handleViewReport = async (reportId: string) => {
    setLoadingId(reportId);
    setErrorMsg(null);
    const res = await getAdminReportUrl(reportId);
    setLoadingId(null);
    if (res.error) {
      setErrorMsg({ id: reportId, text: res.error });
    } else if (res.url) {
      window.open(res.url, "_blank", "noopener,noreferrer");
    }
  };

  return (
    <div className="space-y-4">
      <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-3">
        <div className="flex flex-wrap items-center gap-2 w-full sm:w-auto flex-1">
          <div className="relative w-full sm:w-72">
            <Search className="absolute left-2.5 top-2.5 size-4 text-muted-foreground" />
            <input
              type="text"
              placeholder="Search by candidate name..."
              value={search}
              onChange={(e) => setSearch(e.target.value)}
              className="w-full pl-9 pr-3 py-1.5 rounded-md border border-border bg-background text-xs"
            />
          </div>
          <select
            value={typeFilter}
            onChange={(e) => setTypeFilter(e.target.value)}
            className="rounded-md border border-border bg-background p-1.5 text-xs text-foreground cursor-pointer"
          >
            <option value="all">All Report Types</option>
            <option value="assessment_report">Assessment Report</option>
            <option value="ev_readiness_report">EV Readiness Report</option>
          </select>
        </div>
      </div>

      {filtered.length === 0 ? (
        <div className="flex min-h-[300px] flex-col items-center justify-center rounded-xl border border-dashed border-border bg-card p-8 text-center shadow-xs">
          <div className="flex h-12 w-12 items-center justify-center rounded-full bg-muted text-muted-foreground">
            <FileText className="h-6 w-6" />
          </div>
          <p className="mt-4 max-w-md text-sm font-medium text-foreground">
            No reports generated yet — reports are created automatically once an assessment is finalised. That pipeline is being wired up in an upcoming step.
          </p>
        </div>
      ) : (
        <div className="divide-y divide-border rounded-xl border border-border bg-card overflow-hidden shadow-xs">
          {filtered.map((r) => {
            const isLoading = loadingId === r.id;
            const err = errorMsg?.id === r.id ? errorMsg.text : null;
            return (
              <div key={r.id} className="p-4 space-y-2 hover:bg-muted/30 transition-colors">
                <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3">
                  <div className="space-y-1">
                    <div className="flex items-center gap-2 flex-wrap">
                      <span className="font-semibold text-xs text-foreground">{r.candidate_name}</span>
                      <span className="text-[11px] text-muted-foreground">• {REPORT_TYPE_LABELS[r.report_type] || r.report_type}</span>
                    </div>
                    <div className="flex items-center gap-3 text-[11px] text-muted-foreground">
                      <span className="inline-flex items-center gap-1">
                        <Calendar className="size-3" /> {new Date(r.generated_at).toLocaleDateString()}
                      </span>
                      <span>•</span>
                      <span className="inline-flex items-center gap-1">
                        <UserCheck className="size-3" /> Generated by: <strong className="capitalize text-foreground">{r.generated_by}</strong>
                      </span>
                    </div>
                  </div>

                  <Button
                    onClick={() => handleViewReport(r.id)}
                    disabled={isLoading}
                    variant="outline"
                    size="sm"
                    className="cursor-pointer text-xs font-semibold gap-1.5 self-start sm:self-auto h-8"
                  >
                    {isLoading ? <Loader2 className="size-3.5 animate-spin" /> : <ExternalLink className="size-3.5" />}
                    <span>{isLoading ? "Preparing..." : "View Report"}</span>
                  </Button>
                </div>

                {err && (
                  <div className="flex items-center gap-1.5 text-xs text-destructive pt-1">
                    <AlertCircle className="size-3.5 shrink-0" />
                    <span>{err}</span>
                  </div>
                )}
              </div>
            );
          })}
        </div>
      )}
    </div>
  );
}
